language: ruby
before_install:
  - find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete
  - gem install bundler -v $BUNDLER_VERSION
install: bundle _${BUNDLER_VERSION}_ install --jobs=3 --retry=3
script: bundle _${BUNDLER_VERSION}_ exec rake test
rvm:
- 2.5
- 2.6
- 2.7
- 3.0
env:
  - BUNDLER_VERSION=1.16.6
  - BUNDLER_VERSION=1.17.3
  - BUNDLER_VERSION=2.0.2
  - BUNDLER_VERSION=2.1.4
  - BUNDLER_VERSION=2.2.8
